spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: monge_demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo
    username: root
    password: 123456
  jpa:
    hibernate:
      #????????????ps:???mysql?????,?????"/demo"
      ddl-auto: update
    #jpa?????????Hibernate?sql(??)
    show-sql: true
  redis:
    host: localhost
    database: 0
    port: 6379
#    password: 123456

logging:
  level:
    org.springframework.data.mongodb.core: debug
server:
  port: 8787


